Repository UMC-ON/ON-server, pull requests merged in 2024-09, with the labels that each got.

#84 fix: 프론트 도메인 변경
  src/main/java/com/on/server/global/security/config/SecurityConfig.java
Labels: 해원

#88 [Refactor] 정보/자유게시글 API 리팩토링
  src/main/java/com/on/server/domain/board/application/BoardService.java
  src/main/java/com/on/server/domain/board/presentation/BoardController.java
  src/main/java/com/on/server/domain/post/application/PostService.java
  src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
  src/main/java/com/on/server/domain/post/dto/PostRequestDTO.java
  src/main/java/com/on/server/domain/post/dto/PostResponseDTO.java
  src/main/java/com/on/server/domain/post/dto/WriterInfo.java
  src/main/java/com/on/server/domain/post/presentation/PostController.java
Labels: 지수, refactor

#85 [Refactor] 동행구하기 API 리팩토링
  src/main/java/com/on/server/domain/companyPost/application/CompanyPostService.java
  src/main/java/com/on/server/domain/companyPost/domain/repository/CompanyPostRepository.java
  src/main/java/com/on/server/domain/companyPost/dto/CompanyPostRequestDTO.java
  src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
  src/main/java/com/on/server/domain/companyPost/presentation/CompanyPostController.java
Labels: 채은, refactor

#86 [Refactor] 물품거래 및 스크랩 API 리팩토링
  src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
  src/main/java/com/on/server/domain/marketPost/domain/MarketPost.java
  src/main/java/com/on/server/domain/marketPost/domain/repository/MarketPostRepository.java
  src/main/java/com/on/server/domain/marketPost/dto/MarketPostResponseDTO.java
  src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
  src/main/java/com/on/server/domain/scrap/application/ScrapService.java
  src/main/java/com/on/server/domain/scrap/domain/repository/ScrapRepository.java
  src/main/java/com/on/server/domain/scrap/dto/ScrapRequestDTO.java
  src/main/java/com/on/server/domain/scrap/dto/ScrapResponseDTO.java
  src/main/java/com/on/server/domain/scrap/presentation/ScrapController.java
Labels: 채은, refactor

#87 [Refactor] 동행신청하기 API 리팩토링
  src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
  src/main/java/com/on/server/domain/companyParticipant/dto/CompanyParticipantRequestDTO.java
  src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
Labels: 채은, refactor

#81 [Refactor] 홈 API 리팩토링
  src/main/java/com/on/server/domain/home/application/HomeService.java
  src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
  src/main/java/com/on/server/domain/home/presentation/HomeController.java
  src/main/java/com/on/server/global/util/FormatTimeUtil.java
Labels: 해원, 리나, refactor

#83 [Refactor] 채팅 API 리팩토링
  src/main/java/com/on/server/domain/chat/application/ChatService.java
  src/main/java/com/on/server/domain/chat/domain/SpecialChat.java
  src/main/java/com/on/server/domain/chat/domain/repository/ChatRepository.java
  src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
  src/main/java/com/on/server/domain/chat/dto/ChatListResponseDto.java
  src/main/java/com/on/server/domain/chat/dto/CompanyChatRoomListResponseDto.java
  src/main/java/com/on/server/domain/chat/dto/MarketChatRoomListResponseDto.java
  src/main/java/com/on/server/domain/chat/dto/request/ChatDto.java
  src/main/java/com/on/server/domain/chat/dto/request/MessageDto.java
  src/main/java/com/on/server/domain/chat/dto/response/ChatDto.java
  src/main/java/com/on/server/domain/chat/dto/response/ChatListDto.java
  src/main/java/com/on/server/domain/chat/dto/response/ChatMessageDto.java
  src/main/java/com/on/server/domain/chat/dto/response/CompanyChatDto.java
  src/main/java/com/on/server/domain/chat/dto/response/CompanyChatRoomListDto.java
  src/main/java/com/on/server/domain/chat/dto/response/CompanyRoomDto.java
  src/main/java/com/on/server/domain/chat/dto/response/MarketChatDto.java
  src/main/java/com/on/server/domain/chat/dto/response/MarketChatRoomListDto.java
  src/main/java/com/on/server/domain/chat/dto/response/MarketRoomDto.java
  src/main/java/com/on/server/domain/chat/presentation/ChatController.java
Labels: 해원, refactor

#82 [Refactor] 일기 API 리팩토링
  src/main/java/com/on/server/domain/diary/application/DiaryService.java
  src/main/java/com/on/server/domain/diary/domain/Diary.java
  src/main/java/com/on/server/domain/diary/dto/DiaryDto.java
  src/main/java/com/on/server/domain/diary/presentation/DiaryController.java
Labels: 리나, refactor

#90 [Refactor] 알림 API 리팩토링
  src/main/java/com/on/server/domain/alarm/application/AlertService.java
  src/main/java/com/on/server/domain/alarm/application/FcmService.java
  src/main/java/com/on/server/domain/alarm/domain/Alert.java
  src/main/java/com/on/server/domain/alarm/domain/AlertType.java
  src/main/java/com/on/server/domain/alarm/domain/repository/AlertRepository.java
  src/main/java/com/on/server/domain/alarm/dto/AlertCountDto.java
  src/main/java/com/on/server/domain/alarm/dto/AlertUrlDto.java
  src/main/java/com/on/server/domain/alarm/dto/FcmRequestDto.java
  src/main/java/com/on/server/domain/alarm/dto/Notification.java
  src/main/java/com/on/server/domain/alarm/presentation/AlertController.java
  src/main/java/com/on/server/domain/alarm/presentation/FcmTestController.java
  src/main/java/com/on/server/domain/comment/application/CommentService.java
  src/main/java/com/on/server/domain/comment/presentation/CommentController.java
  src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
  src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
  src/main/java/com/on/server/domain/post/domain/repository/PostRepository.java
Labels: 리나, refactor

#93 fix: 채팅 알림 추가 및 기존 알림 수정
  src/main/java/com/on/server/domain/alarm/application/AlertService.java
  src/main/java/com/on/server/domain/alarm/domain/AlertType.java
  src/main/java/com/on/server/domain/chat/application/ChatService.java
  src/main/java/com/on/server/domain/chat/presentation/ChatController.java
  src/main/java/com/on/server/domain/comment/application/CommentService.java
  src/main/java/com/on/server/domain/comment/presentation/CommentController.java
  src/main/java/com/on/server/domain/companyParticipant/application/CompanyParticipantService.java
  src/main/java/com/on/server/domain/companyParticipant/presentation/CompanyParticipantController.java
  src/main/java/com/on/server/domain/marketPost/application/MarketPostService.java
  src/main/java/com/on/server/domain/marketPost/presentation/MarketPostController.java
  src/main/java/com/on/server/global/common/ResponseCode.java
Labels: 리나, feature

#94 feat: 알림 리스트 알림 id 및 읽음 상태 추가
  src/main/java/com/on/server/domain/alarm/application/AlertService.java
  src/main/java/com/on/server/domain/alarm/dto/AlertListResponseDto.java
Labels: 리나
