Repository UMC-ON/ON-server, pull requests merged in 2024-11, with the labels that each got.

#95 [Feature & Fix] 채팅 API 수정
  src/main/java/com/on/server/domain/chat/application/ChatService.java
  src/main/java/com/on/server/domain/chat/domain/repository/ChattingRoomRepository.java
  src/main/java/com/on/server/domain/chat/dto/response/ChatListDto.java
  src/main/java/com/on/server/domain/chat/dto/response/CompanyChatDto.java
Labels: enhancement, 해원, feature

#103 feat: 채팅 알림 type 마켓, 동행 구분
  src/main/java/com/on/server/domain/alarm/domain/AlertType.java
  src/main/java/com/on/server/domain/chat/application/ChatService.java
Labels: 리나, feature

#104 fix: User Service Layer @Transcational 안 붙은 method 수정
  src/main/java/com/on/server/domain/user/application/UserService.java
Labels: bug, 상제

#106 fix: id/pw찾기 api security config 허용
  src/main/java/com/on/server/domain/user/presentation/UserController.java
  src/main/java/com/on/server/global/security/config/SecurityConfig.java
Labels: bug

#110 fix: 일기 작성 시 선택한 날짜로 저장하도록 수정
  src/main/java/com/on/server/domain/diary/application/DiaryService.java
  src/main/java/com/on/server/domain/diary/domain/Diary.java
  src/main/java/com/on/server/domain/diary/dto/DiaryDto.java
  src/main/java/com/on/server/domain/diary/dto/DiaryRequestDto.java
Labels: 리나

#112 fix: 사용자 나이 대신 생년월일로 수정
  src/main/java/com/on/server/domain/companyPost/dto/CompanyPostResponseDTO.java
  src/main/java/com/on/server/domain/home/dto/CompanyBoardListResponseDto.java
  src/main/java/com/on/server/domain/user/application/UserService.java
  src/main/java/com/on/server/domain/user/domain/User.java
  src/main/java/com/on/server/domain/user/domain/repository/UserRepository.java
  src/main/java/com/on/server/domain/user/dto/request/FindIDRequestDto.java
  src/main/java/com/on/server/domain/user/dto/request/SendPWAuthNumRequestDto.java
  src/main/java/com/on/server/domain/user/dto/request/SignUpRequestDto.java
Labels: feature

#113 fix: Exception handler 수정
  src/main/java/com/on/server/global/common/GlobalExceptionHandler.java
  src/main/java/com/on/server/global/common/ResponseType.java
Labels: wontfix
